### ISSUE TITLE
Evaluation of two previously evaluated models 

### ISSUE THREAD

**Issue by lfoppiano** [ryabhmd/scilons-eval#8]
Aloha. How about testing the evaluation on these two models we trained in the past? 
- https://huggingface.co/scilons/sci-jina-bert-base-seqlen-512
- https://huggingface.co/scilons/roberta-base-128

I'd like to evaluate whether they follow the evaluation with the models that I did which were kind of specific to materials science and measurements

These were my evaluation (the best models scores 76-77% F1 on materials and 85-86% on measurements)

- [roberta-base-128.measurements.eval.txt](https://github.com/ryabhmd/scilons-eval/files/15344265/roberta-base-128.measurements.eval.txt)
- [roberta-base-128.materials.eval.txt](https://github.com/ryabhmd/scilons-eval/files/15344266/roberta-base-128.materials.eval.txt)

- [sci-jina-bert-base-seqlen-512.measurements.eval.txt](https://github.com/ryabhmd/scilons-eval/files/15344267/sci-jina-bert-base-seqlen-512.measurements.eval.txt)
- [sci-jina-bert-base-seqlen-512.materials.eval.txt](https://github.com/ryabhmd/scilons-eval/files/15344268/sci-jina-bert-base-seqlen-512.materials.eval.txt)

**Comment by ryabhmd** [comment]
Hey @lfoppiano 😄 
Can you please clarify which task exactly you evaluated in the .txt files you attached, and which dataset(s) did you use? 
It's a bit unclear to me at the moment.

**Comment by lfoppiano** [comment]
Hi @ryabhmd, I evaluated only the NER task using two specialised datasets. You can forget about my results and the datasets I used. 😉 I just post them so I don't have to fish them back from discord. 😄 

I was just wondering whether you could just run your evaluation on the two models.

**Comment by ryabhmd** [comment]
[sci-jina-bert-base-seqlen-512.csv](https://github.com/user-attachments/files/15530179/sci-jina-bert-base-seqlen-512.csv)
[roberta-base-128.csv](https://github.com/user-attachments/files/15530183/roberta-base-128.csv)

Here are the results of the two mentioned models 😄.
Note that I couldn't evaluate sci-jina on NER and PICO tasks, since the code is built by using AutoModelForTokenClassification for fine-tuning on those datasets and the model throws an error if loaded with this class (I guess it's not in its config?). Let me know what you think we should do with these cases.

**Comment by lfoppiano** [comment]
Hi @ryabhmd, 
   thanks. Without the NER it's hard to compare, it seems that JINA model works better on the tasks that was evaluated. 😅 

If I may give you a comment. The results seems to have different approximations, and order, so it's not straightforward to compare. Also names have different uppercase/lowercase (e.g. paperfield is not found roberta-base)

**Comment by ryabhmd** [comment]
@lfoppiano the difference is because the .csv for JINA was constructed manually by myself. I couldn't run the code that evaluated all tasks at once because of the problem with NER, so I evaluated on each task separately and saved everything in a csv manually. You can ignore this for now, for future evaluations this can of course be fixed :D

**Comment by lfoppiano** [comment]
OK. Thanks. 

Unfortunately since the NER tasks cannot be evaluated on the jina model, I could not really make any conclusions. I might conclude only that this may have been the cause of the problems in the other evaluation.
